baseURL = "/"
title = "init8"
author = "init8"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Google Analytics Id 
ga_analytics = "G-6MGE237E3H"

# Google tag manager
google_tag_manager_id = "G-6MGE237E3H"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/IMG_6039.png"
    # main = "img/logo/logo.svg"
    alt = "init8 Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "init8"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "init8"
    meta_og_type = "website"
    meta_og_url = "https://init8.jp"
    # meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "init8 wa totemo hajiketa hitotachi desu."
    # meta_twitter_card = "summary_large_image"
    # meta_twitter_site = "@username"
    # meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    identifier = "Achievements"
    name = "Achievements"
    url = "/achievements/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/int8-jp"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
